site_name: "NCOR"
repo_url: https://github.com/johnbeve/NCOR-Test/
site_description: NCOR Homepage
site_author: John Beverley
edit_uri: '?query=root/NCOR-Test/docs/'

theme:
  name: material
  logo: assets/ncor-logo.png
  palette:
    primary: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  hide:
    - toc

extra_css:
  - stylesheets/extra.css
  
nav:
  - About: index.md
  - NCOR Labs: 
    - Ontology 101 WG: ontology-101-wg.md
    - Common Core Ontologies WG: cco-wg.md
    - Semantic Mappings WG: semantic-map-wg.md
    #- Industrial Ontologies WG: iof-wg.md
    - Document Acts WG: d-acts-wg.md
  - Affiliates: 
    - People: people.md
    - Organizations: organizations.md
  - Training: 
    - NCOR Pathways: 
      - Overview: training.md
      - Foundations: 
        - Overview: foundations.md
      - Associate: associate.md
      - Specialist: specialists.md
    - Bootcamps: bootcamps.md
    - Open-Access Resources: open-access-courses.md
  - News: events.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/search/results/all/?fetchDeterministicClustersOnly=true&heroEntityKey=urn%3Ali%3Afsd_profile%3AACoAAAApbuYB2XIdgO4B_zTBN4RKTGW0OqEylxg&keywords=barry%20smith&origin=RICH_QUERY_SUGGESTION&position=0&searchId=4c7bf265-d8f5-4954-8829-71ac1ab78134&sid=6!x&spellCorrectionEnabled=false
    - icon: fontawesome/brands/github
      link: https://github.com/BFO-ontology/BFO-2020
    - icon: octicons/mail-16
      link: mailto:johnbeve@buffalo.edu

markdown_extensions:
    - attr_list